- callbacks/aspect_inject.go
- callbacks/aspect_inject_test.go
- callbacks/manager.go
- callbacks/template/template_test.go
- compose/tool_node.go
- compose/utils.go
- flow/retriever/multiquery/multi_query.go
- flow/retriever/router/router.go
- flow/retriever/utils/utils.go
Change-Id: Ic602e6d3af3dec90d4ff26bc194e764a38617c7a
en:
zh(optional):
> refactor: SetRunInfo

- compose/graph.go
- compose/graph_test.go
- compose/introspect.go
Change-Id: I945424ec5fdbd0307330aa0bf0b746f71f11a3b8
en:
zh(optional):
> feat: expose graph name in GraphInfo

- schema/document.go
- schema/document_test.go
- refactor schema.Document builtin extra methods
- rename few method names and extra key
- add sparse vector getter & setter（basically for indexer and retrieve）
- 调整 schema.Document extra 的部分内置方法
- 修改部分方法名称与 key
- 新增 sparse vector getter setter，供 indexer & retriever 使用
en:
zh(optional):
> refactor: document extra methods

- components/document/interface.go
- components/document/option.go
- components/types.go
- compose/chain.go
- compose/chain_branch.go
- compose/chain_parallel.go
- compose/component_to_graph_node.go
- compose/graph.go
- compose/graph_call_options.go
- internal/mock/components/document/document_mock.go
- utils/callbacks/template_test.go
> chore: remove deprecated LoaderSplitter

- components/prompt/chat_template_test.go
- compose/chain.go
- compose/dag.go
- compose/field_mapping.go
- compose/generic_graph.go
- compose/graph.go
- compose/graph_compile_options.go
- compose/graph_manager.go
- compose/graph_node.go
- compose/graph_run.go
- compose/graph_test.go
- compose/introspect.go
- compose/pregel.go
- compose/runnable.go
- compose/state.go
- compose/state_test.go
- compose/stream_concat.go
- compose/stream_concat_test.go
- compose/tool_node_test.go
- compose/types.go
- compose/types_composable.go
- compose/workflow.go
- compose/workflow_test.go
- schema/message_test.go
- schema/stream_test.go
> refactor: gragp & workflow

- flow/agent/multiagent/host/compose.go
- flow/agent/multiagent/host/compose_test.go
- flow/agent/multiagent/host/types.go
Change-Id: Iffa3e4a6ed677bffff7bbd0f42d3d64d8adb2c18
en:
zh(optional):
> feat: add StreamToolCallChecker to host multi-agent config

- components/model/callback_extra.go
- components/model/option.go
- components/model/option_test.go
- schema/tool_choice.go
refactor: remove tool_choice in model callback input
chat model tool choice 重构
en:
1. remove tool choice (type any) from callback input
2. add tool choice string type def and enums
3. add model common call option with tool choice
zh(optional): 
1. 移除 callback input 中 any 类型的 tool choice
2. 新增 string 类型 tool choice 定义，给出枚举值
3. model call option 支持请求级别配置 tool choice
> refactor: chat model tool choice

- components/model/callback_extra.go
> feat: deprecate ToolChoice in model CallbackInput

- components/model/option.go
- components/model/option_test.go
- schema/tool.go
feat: add tool choice definition, call options add tools and tool choice
feat
en:
Add chat model tool choice definition and enums.
Common call options for chat model now supports passing tools and tool choice.
zh(optional): 
新增 tool choice 定义与枚举值
Chat model 通用 call options 支持传递 tools 和 tool choice
> feat: add tool choice definition, call options add tools and tool choice

- .testcoverage.yml
- compose/stream_concat.go
- compose/stream_concat_test.go
- compose/tool_node_test.go
- compose/workflow_test.go
- internal/concat.go
- schema/message.go
> fix: move concat & concat message extra by ConcatItems

- compose/dag_test.go
- compose/graph.go
- compose/graph_compile_options.go
- compose/graph_run.go
- compose/state.go
- compose/state_test.go
- flow/agent/react/react.go
- flow/agent/react/react_test.go
> feat: add ProcessState & deprecate GetState

- .github/workflows/pr-check.yml
- .github/workflows/tests.yml
- .golangci.yaml
- flow/agent/multiagent/host/callback.go
- flow/agent/multiagent/host/compose.go
- flow/agent/multiagent/host/compose_test.go
- flow/agent/multiagent/host/types.go
- flow/agent/react/react.go
- flow/agent/react/react_test.go
feat
react agent 和 host multi-agent 支持导出为 AnyGraph，可直接进入编排。
refactor agents to support graph composition
- Implement GraphFlow interface for react.Agent and host.MultiAgent
- Add support for proper node path designation in subgraphs
- Maintain backward compatibility for direct usage
> feat: react agent and host multi-agent can be composed directly as AnyGraph

- schema/stream.go
- schema/stream_copy_external_test.go
- schema/stream_test.go
fix
修复复制后的 stream 锁粒度过大导致的性能问题
en:
zh(optional):
> fix: unfair lock behavior in copied stream

- compose/dag.go
- compose/graph.go
- compose/graph_manager.go
- compose/graph_run.go
- compose/graph_test.go
- compose/pregel.go
> feat: add dag branch

- compose/utils.go
- internal/callbacks/inject.go
fix: correctly set and pass context between callback handlers in streaming scenarios
> fix: ctx in stream callback handlers

- _typos.toml
- compose/field_mapping.go
- compose/workflow_test.go
feat: workflow can create FieldMapping from or to fields of maps
1. create FieldMapping from map fields to struct fields
2. create FieldMapping from struct fields to map fields
3. create FieldMapping from map fields to map fields
> feat: workflow can create FieldMapping from or to fields of maps

- compose/graph_compile_options.go
- compose/state.go
> feat: remove GetState and WithGetStateEnable already deprecated

- flow/agent/multiagent/host/types.go
- flow/agent/react/react.go
There are ChatModels that emits message trunks with empty content and empty tool calls first, then emits message chunks with non-empty tool calls.
When given message Stream like this, the default StreamToolCallChecker will not be able to tell the Stream contains tool call, because the first chunk would not contain tool call.
This PR fix this by modifying the behavior of default StreamToolCallChecker by skipping message chunks containing empty Content at the front.
> fix: default stream tool call checker skips empty chunks at the front

- .gitignore
- callbacks/interface.go
- callbacks/interface_test.go
- schema/message.go
InitCallbackHandlers always overrides the existing GlobalHandlers, which makes it difficult to inject separate Callback Handlers for different scenarios. Therefore, the AppendGlobalHandlers method has been added.
> feat: add AppendGlobalHandlers instead of InitCallbackHandlers

- compose/field_mapping.go
- compose/workflow_test.go
feat: workflow supports mapping from nested fields and to nested fields
1. can create field mapping from fields of nested structs or nested maps
2. can create field mapping to fields of nested structs or nested maps
3. use a new set of API to create nested field mapping
4. allow an intermediate level of the mapping 'source' to be an interface, will defer type check to request time: 
e.g.
```
// the output of from_node_key is map[string]any.
// at request time, the value for key 'field1' is another map with a key 'field2'
// when Compiling the workflow, we only know the value type of the map is 'any'.
// So we will defer type checking to request time.
AddInput("from_node_key", FromFieldPath([]string{"field1", "field2"})
```
> feat: workflow supports mapping from nested fields and to nested fields

- compose/field_mapping.go
- compose/workflow_test.go
workflow can map to a internal 'any' value's multiple fields simultaneously
> fix: assign to any's fields simultaneously

- compose/graph_compile_options.go
- compose/types.go
> feat: modify trigger mode comment

- compose/state.go
> feat: add deprecated GetState

- compose/error.go
- compose/error_test.go
This PR adds the `Unwrap() error` method to the `internalError` struct in the `compose` package to support Go's error unwrapping mechanism (`errors.Unwrap` and `errors.Is`). It also adds a test case to verify proper handling of `context.Canceled` errors.
> feat: Add Unwrap method to compose internalError

- flow/agent/multiagent/host/callback.go
- flow/agent/multiagent/host/compose.go
- flow/agent/multiagent/host/compose_test.go
- flow/agent/multiagent/host/types.go
feat: host multi-agent now supports recognizing multiple intents at the same time.
1. Previously, host multi-agent can only pick one specialist per run. Recognizing multiple intents would result in error.
2. Now, if the host picks more than one specialist at the same time, all the chosen specialists will be executed in parallel.
3. If so, a Summarizer node will summarize these specialists' output messages into a single message.
4. Optionally, host multi-agent can accept a Summarizer configuration, which is a BaseChatModel with a system prompt.
5. If no Summarizer specified by the user, a default Summarizer that simply concatenates all the message contents will be used.
> feat: support multiple intents in host multi-agent

- compose/field_mapping.go
- compose/workflow.go
- compose/workflow_test.go
fix a bug when a workflow node's all inputs are static values, the nested field paths are wrong. 
Now all the field paths for the node's inputs, including nested field paths, are properly structured.
> fix: support using static values for all input

- components/tool/utils/create_options.go
- components/tool/utils/invokable_func_test.go
Previously, defaultSchemaCustomizer will treat all enum tag values as string literals. This makes it impossible to set Integer or Float type enum values using defaultSchemaCustomer. Now we fix it to parse enum tag values according to the corresponding struct field's actual type.
> fix: defaultSchemaCustomizer now correctly parses enum tag values to corresponding field type

- flow/agent/multiagent/host/callback.go
- flow/agent/multiagent/host/compose_test.go
- flow/agent/multiagent/host/types.go
Previously, in the scenario where Host Multi-Agent streamed answers directly from the Host, using the OnHandOff callback simultaneously would cause the loss of streaming effects, resulting in the direct output of the Host's full answer in one message chunk. This PR fixes this issue.
> fix: supports direct streaming output from host while using host multi-agent callback

- compose/checkpoint.go
> fix: trigger checkpoint restore in loop

- compose/tool_node.go
- compose/tool_node_test.go
- schema/message.go
> feat: add ToolCallName to schema.Message

- compose/field_mapping.go
- compose/graph.go
- compose/workflow_test.go
- internal/concat.go
- internal/concat_test.go
This PR refactors the field mapping logic in `compose/field_mapping.go` to improve robustness and handling of complex/dynamic types, particularly those involving interfaces.
**Key Changes:**
*   **Enhanced Dynamic Type Handling:** Introduced mechanisms (e.g., `uncheckedSourcePaths`, `remainingPaths` in `checkAndExtractFieldType`) to defer parts of field path validation and type resolution to runtime. This allows for more flexible mapping when source or target types are not fully known at compile time (e.g., due to `interface{}`).
*   **Simplified Error Handling:** Refactored internal functions like `convertTo` and `assignOne` to remove explicit error returns, relying more on implicit panics for unrecoverable errors. The key idea is all expected errors are either checked at compile time or …
> fix: make field mapping more robust and concise

- compose/utils.go
- internal/callbacks/inject.go
deep copy callback handlers when AppendHandlers, to avoid lost updates when two concurrent child processes appending to the same Context.
> fix: deep copy callback handlers when AppendHandlers

- compose/graph.go
workflow branch will skip data passing to successor nodes. Previously, these kind of branches won't add the branch 'from node' and 'end nodes' to graph's start node and end node list, which does not make sense
> fix: add to start and end node list even if the branch skips data

- compose/graph.go
- compose/graph_compile_options.go
- compose/state.go
> feat(compose): remove GetState & use eager execution by default in graph with all predecessor

- flow/agent/react/react.go
fix: A bug fix
使用正确的 context 调用 `toolCallChecker`
en:
The ignored ctx parameter leads to the actual use of NewAgent ctx parameter when calling toolCallChecker.
The default toolCallChecker works well with that, because it does not use ctx.
When a custom toolCallChecker is specified, this issue is exposed.
zh(optional):
忽略的 ctx 参数导致调用 toolCallChecker 时实际使用的是 NewAgent 的 ctx 参数。
默认的 toolCallChecker 能正常工作，因为它并没有使用 ctx。
但当自定义 toolCallChecker 时，暴露了该问题。
None.
None.
> fix(flow_react): use correct context to call `toolCallChecker`

- .testcoverage.yml
- flow/agent/react/option.go
- flow/agent/react/option_test.go
- flow/agent/react/react_test.go
- schema/tool_test.go
Add WithTools, which is a convenience function that configures a React agent with a list of tools.
It performs two essential operations:
1. Extracts tool information for the chat model to understand available tools
2. Registers the actual tool implementations for execution
> feat: add WithTools convenience function to react agent

- compose/checkpoint_test.go
- compose/graph_call_options.go
- compose/graph_manager.go
- compose/graph_run.go
> feat: support cancel interrupt
