compose/graph_call_options.go
compose/graph_call_options_test.go
compose/graph_run.go
compose/graph_test.go
compose/utils.go

remove the deprecated internal fields nodeHandlers and graphHandlers

feat: remove node/graph cb

---

callbacks/aspect_inject.go
callbacks/doc.go
compose/tool_node.go
flow/retriever/multiquery/multi_query.go
flow/retriever/router/router.go
flow/retriever/utils/utils.go
internal/callbacks/inject.go
utils/callbacks/template_test.go

Change-Id: Icda09f28bb256a7406cafc18a0a1b6f3dc635593
en:
zh(optional):

refactor: change function name of SetRunInfo

---

compose/utils.go
internal/callbacks/inject.go
utils/generic/generic.go
utils/generic/generic_test.go

Change-Id: Ib1945f97cb45832e3b3e76f06f51c3c7c68645e1
en:
zh(optional):

fix: not expected: in place reverse

---

flow/agent/react/react.go

Change-Id: Idcea4add7a1d60054089078002ba87856757b0d5
en:
zh(optional):

refactor: use GetState with ReAct agent

---

callbacks/aspect_inject_test.go
internal/callbacks/inject.go
internal/callbacks/manager.go

fix: global callbacks repeated in AppendHandlers

---

README.md
README.zh_CN.md

Change-Id: I1caac41c32d01ac49704fd6a2298821ab9f6311e
en:
zh(optional):

add dependencies to readme

---

flow/agent/react/react.go

feat: add StreamToolCallChecker to react agent config

---

schema/stream.go

Change-Id: Ie5fc851268f4552e405a20439378fa5457b5775c
en:
zh(optional):

chore: change comment for ErrNoValue

---

README.md

Change-Id: I6715f87cbf415f7c33abe9d0e64c713381745157
en:
zh(optional):

≠≠Chore/comment

---

components/retriever/interface.go

feat: remove xxx from retriever comment

---

compose/types_lambda.go

fix: misspell word

---

flow/agent/react/react.go

fix: react agent invalid copy when modifying message

---

flow/agent/react/react_test.go

fix: add ut of react agent for testing messages modifier

---

.github/workflows/tests.yml

ci: add workflow of break changes comment

ci: add workflow of break changes comment

---

compose/tool_node.go
compose/tool_node_test.go

feat: add tool list option to tools node

---

schema/message.go
schema/message_test.go

feat: add logprobs definition

---

compose/field_mapping.go
compose/workflow_test.go

fix: nested field mapping to map.(non-ptr)struct.field

fix: nested field mapping to map.(non-ptr)struct.field

---

flow/agent/multiagent/host/types.go
flow/agent/react/react.go

fix: return false if meet EOF in firstChunkStreamToolCallChecker

---

components/tool/utils/invokable_func.go
components/tool/utils/invokable_func_test.go
components/tool/utils/streamable_func.go
components/tool/utils/streamable_func_test.go

feat: add InferToolWithOption and InferStreamToolWithOption for tool utils

feat: tool utils add InferToolWithOption

---

compose/tool_node.go
compose/tool_node_test.go

feat: ToolsNode provides util function to get tool call ID from context

feat: ToolsNode provides util function to get tool call ID from context

---

compose/branch.go
compose/dag.go
compose/field_mapping.go
compose/generic_graph.go
compose/graph.go
compose/graph_manager.go
compose/graph_run.go
compose/pregel.go
compose/workflow.go
compose/workflow_test.go

feat: workflow dependency, branch and static values

feat: workflow dependency, branch and static values

---

components/prompt/chat_template_test.go
compose/branch.go
compose/chain.go
compose/checkpoint.go
compose/checkpoint_test.go
compose/dag.go
compose/generic_graph.go
compose/generic_helper.go
compose/graph.go
compose/graph_call_options.go
compose/graph_compile_options.go
compose/graph_manager.go
compose/graph_node.go
compose/graph_run.go
compose/graph_test.go
compose/interrupt.go
compose/introspect.go
compose/pregel.go
compose/runnable.go
compose/state.go
compose/stream_concat.go
compose/types_composable.go
compose/workflow.go
compose/workflow_test.go
go.mod
go.sum
internal/serialization/serialization.go
internal/serialization/serialization_test.go
schema/stream.go

feat: graph checkpoint

---

compose/graph.go
compose/graph_test.go
compose/introspect.go

feat: add state type in graph info

---

internal/serialization/serialization.go

feat: register schema type

---

compose/field_mapping.go
compose/workflow.go
compose/workflow_test.go

1. when user specifies field mappings targeting fields of 'interface{}' type, create a 'map[string]any' and maps to keys of this map.
2. during workflow compile, validate field mappings so that these two target paths returns error: A, A.B

feat: support mapping to field of any

---

README.md
README.zh_CN.md

docs: fix license file link

---

compose/checkpoint.go
compose/checkpoint_test.go
compose/graph_run.go
compose/interrupt.go
compose/workflow.go
compose/workflow_test.go
flow/agent/react/react_test.go

feat: node interrupt

---

compose/field_mapping.go
compose/workflow_test.go

1. can create field mapping from map key with a nil value
2. can create field mapping from struct field with a nil value

feat: support field mapping from map key with nil value or nil struct field

---

compose/graph.go

feat: add GetPath method to NodePath

---

components/tool/utils/create_options.go
components/tool/utils/invokable_func_test.go

fix: append enum tag

---

compose/error.go
compose/error_test.go
compose/graph_run.go
compose/graph_test.go
compose/interrupt.go
compose/runnable.go
compose/workflow_test.go

feat: optimize error info

---

components/model/interface.go
compose/chain.go
compose/chain_branch.go
compose/chain_parallel.go
compose/component_to_graph_node.go
compose/graph.go
compose/workflow.go
flow/agent/multiagent/host/compose.go
flow/agent/multiagent/host/types.go
flow/agent/react/option.go
flow/agent/react/option_test.go
flow/agent/react/react.go
flow/agent/utils.go
internal/channel.go
internal/channel_test.go
internal/mock/components/model/ChatModel_mock.go
schema/message.go

Change-Id: Iff947c8c64754aa8a0fe48131d9dad1ee988da00
en:
zh(optional):

feat: add ToolCallingChatModel interface & react agent: add MessageFuture option

---

compose/chain.go
compose/chain_test.go

fix: chain branch and parallel with node key

fix: chain branch and parallel with node key

---

compose/checkpoint_test.go
compose/graph_run.go
compose/state.go
compose/utils.go

feat: trigger graph callback in graph run

---

flow/agent/multiagent/host/compose.go
flow/agent/multiagent/host/compose_test.go
flow/agent/multiagent/host/types.go

Change-Id: If8114312f48ba2d7cc183202342b458e64a887c4
en:
zh(optional):

fix: fix multi-agent chat model

---

compose/checkpoint_test.go
compose/graph_run.go

feat: support interrupt before start node

---

internal/serialization/serialization.go
internal/serialization/serialization_test.go

fix: register serialization type

---

flow/agent/react/option.go

feat: add WithToolList to react agent

---

callbacks/aspect_inject.go
callbacks/aspect_inject_test.go
internal/callbacks/inject.go

feat: add EnsureRunInfo

---

components/tool/utils/error_handler.go
components/tool/utils/error_handler_test.go

feat: add tool error wrapper

---

.github/workflows/tag-notification.yml

ci: add tag notice

---

components/tool/utils/streamable_func.go

Change-Id: I5fb9a83bac79d8b2853d94dd2555f0ce41838ff4
en:
zh(optional):

fix: small fix in comments

---

callbacks/aspect_inject.go
callbacks/aspect_inject_test.go
compose/error.go
compose/error_test.go
compose/tool_node.go
compose/utils.go
internal/callbacks/inject.go
internal/callbacks/manager.go
utils/callbacks/template_test.go

feat: limit a RunInfo callback to be triggered only once

---

compose/interrupt.go

feat: support extract sub graph interrupt error

---

components/prompt/chat_template.go

feat: add ensure run info to default prompt

---

internal/serialization/serialization.go
internal/serialization/serialization_test.go

feat: use Marshaler/Unmarshaler of struct if defined

---

compose/field_mapping.go
compose/workflow_test.go

fix: field mapping type check

---

compose/graph_manager.go
compose/graph_run.go

Change-Id: I01fb7650fba497b32fce8be95d3cb2810bfd4f67
en:
zh(optional):

feat: (compose) implement task manager 'done' by UnboundedChan

---

compose/checkpoint.go
compose/generic_graph.go
compose/graph_run.go

feat: optimize the method of checking sub graph

---

compose/graph_manager.go
compose/graph_run.go

Change-Id: Iefed4dc580c336c3e715113e29df520bd39c3eb3
en:
zh(optional):

fix: (graph run) cancel after all running tasks finished

---

compose/graph.go
compose/graph_compile_options.go

feat: add WithEagerExecution

---

components/prompt/chat_template_test.go
schema/message.go

feat: support multi content format

---

compose/dag.go
compose/values_merge.go
internal/serialization/serialization_test.go
schema/stream.go
schema/stream_test.go

Change-Id: If3bfb6961ab035f9bb701f6957bec4458511daa8
en:
zh(optional):

feat: (stream) implement MergeNamedStreamReaders & SourceEOF

---

compose/checkpoint.go
compose/checkpoint_test.go
compose/error_test.go
compose/graph_run.go
compose/interrupt.go
compose/tool_node.go
compose/tool_node_test.go
internal/serialization/serialization.go

feat: support tool rerun

---

internal/concat.go

fix: when concatenating maps, if there is only one element for a specific map key, now we will not try to concatenate the slice, just use the only element. 
Also removed some unused code in the same file.

fix: add shortcut when concatenating a map key with only one element

---

components/tool/utils/common.go
components/tool/utils/common_test.go
components/tool/utils/invokable_func.go
components/tool/utils/streamable_func.go

This PR optimizes tool execution output format handling by avoiding unnecessary JSON escaping for string-type results and extracting common functionality for better code reusability.
- `components/tool/utils/common.go` - Extracted common utility function
- `components/tool/utils/common_test.go` - Comprehensive unit test coverage
- `components/tool/utils/invokable_func.go` - Uses refactored common function
- `components/tool/utils/streamable_func.go` - Uses refactored common function and fixes variable bug
```go
// New common function
func marshalString(resp any) (string, error) {
if rs, ok := resp.(string); ok {
return rs, nil  // Direct string return, no escaping
}
return sonic.MarshalString(resp)  // JSON serialization for other types
}
```
```go
// Before
if rs, ok := …
```

feat: optimize tool output format with marshalString refactoring

---

adk/agent_tool.go
adk/agent_tool_test.go
adk/chatmodel.go
adk/chatmodel_test.go
adk/flow.go
adk/flow_test.go
adk/interface.go
adk/runctx.go
adk/runner.go
adk/runner_test.go
adk/utils.go
adk/workflow.go
adk/workflow_test.go

feat: agent as tool

---

compose/checkpoint.go
compose/checkpoint_test.go
compose/graph_call_options.go
compose/graph_run.go

feat: add ForceNewRun option

---

compose/field_mapping.go
compose/workflow_test.go

Previously, workflow field mappings can only specify 'from field' or 'from path', which limits the from field or path to be along struct or map fields. 
There are cases where we want to extract from more complex paths such as array.
This PR provides a new option to specify a 'custom extractor function' when declaring a field mapping.
```
// WithCustomExtractor sets a custom extractor function for the FieldMapping.
// The extractor function is used to extract a value from the 'source' of the FieldMapping.
// NOTE: if specified in this way, Eino can only check the validity of the field mapping at request time..
func WithCustomExtractor(extractor func(input any) (any, error)) FieldMappingOption {
return func(m *FieldMapping) {
m.customExtractor = extractor
}
}
```

feat: can use custom extractor function in workflow field mappings

---

schema/message.go

feat: optimize Message string

---

compose/utils.go
internal/callbacks/inject.go

This reverts commit 71ee93258839589eb18d231300cb35a1654c51ef.
en:
zh(optional):

Revert "fix: deep copy callback handlers when AppendHandlers (#320)"

---

compose/checkpoint.go
compose/graph_call_options.go
compose/graph_run.go

feat: add WithWritterCheckPointID

---

schema/tool.go

feat: ToolInfo add Extra field

---

components/document/option.go
components/document/option_test.go

fix(loader): export fields of loader common options

---

compose/stream_concat_test.go
schema/stream_copy_external_test.go

fix: ut data race

---

adk/utils.go
go.mod
go.sum

fix(adk): use uuid as mock transfer tool call id

---

internal/serialization/serialization.go

fix: register PromptTokenDetails serialization

---

adk/call_option.go
adk/flow.go

feat: support skip transfer messages

---

adk/flow.go

feat(adk): history entry support user input

---

compose/graph_node.go
flow/agent/react/react.go
internal/callbacks/interface.go

docs: optimize some field comments of AgentConfig

---

compose/error.go

fix: optimize internal error format

---

compose/graph_run.go
compose/runnable.go
compose/workflow_test.go

fix: empty end value

---

compose/error.go
compose/runnable.go

fix: optimize stream wrapper error

---

compose/graph_manager.go
compose/graph_test.go

#	compose/graph_test.go
en:
zh(optional):

fix: report error if end node has been skipped

---

components/tool/utils/invokable_func.go

refactor
just remove an incorrect function comment
en:
zh(optional): 
no

refactor: remove incorrect function comment

---

adk/flow.go
adk/interrupt_test.go
adk/runctx.go

fix: encode agent event wrapper & input message in history rewrite

---

adk/flow.go
adk/interface.go
adk/interrupt_test.go
adk/runctx.go
adk/utils.go

refactor: change run path from string to RunStep

---

adk/call_option.go
adk/runner.go

feat(adk): support WithSessionValues agent run option

---

schema/message.go

feat: print reasoning content if exist

---

adk/chatmodel.go
adk/prebuilt/planexecute/plan_execute.go
adk/prebuilt/planexecute/plan_execute_test.go
adk/react.go
adk/react_test.go

feat: use MaxIterations instead of MaxSteps for ChatModelAgent

---

compose/checkpoint_test.go
compose/graph_manager.go

feat: support prehandler interrupt

---

adk/react.go

fix(adk): ChatModelAgent return directly tool panic

---

adk/agent_tool.go

feat: support agent tool input schema

---

internal/serialization/serialization.go
internal/serialization/serialization_test.go

fix: empty slice & empty fields serialization

---

components/tool/utils/create_options.go
components/tool/utils/invokable_func.go
components/tool/utils/invokable_func_test.go
go.mod
go.sum

InferTool supports WithSchemaModifier option and is compatible with WithSchemaCustomizer
feat&fix
en:
1. InferTool supports WithSchemaModifier option.
2. Fix WithSchemaCustomizer compatibility issues.
zh(optional):

feat: InferTool supports WithSchemaModifier option and is compatible with WithSchemaCustomizer
